name = "docbuild"
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "OSforGFF"
path = ".."

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "v4.28.0"

[[lean_lib]]
name = "docbuild"
