import Mathlib.Analysis.LocallyConvex.WithSeminorms
import Mathlib.Analysis.InnerProductSpace.Basic
import Mathlib.Data.Real.Sqrt

/-!
# Seminorm bounds from continuity (Gaussian setup)

If the (squared) covariance seminorm `f ↦ ‖T f‖²` is continuous and the topology on `E` is
generated by a family of seminorms `p`, then `f ↦ ‖T f‖` is bounded by a finite supremum of
seminorms from the family.

First step in relating the covariance to a *countable* generating family coming
from nuclearity hypotheses.
-/

open scoped BigOperators ENNReal NNReal

namespace OSforGFF

noncomputable section

namespace MinlosGaussianSeminormBounds

variable {E : Type*} [AddCommGroup E] [Module ℝ E] [TopologicalSpace E]
variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]

/-- If `f ↦ ‖T f‖²` is continuous, then `f ↦ ‖T f‖` is continuous. -/
theorem continuous_norm_of_continuous_norm_sq (T : E →ₗ[ℝ] H)
    (h_sq : Continuous fun f : E => (‖T f‖ ^ 2 : ℝ)) :
    Continuous fun f : E => ‖T f‖ := by
  have h_sqrt : Continuous fun f : E => Real.sqrt (‖T f‖ ^ 2 : ℝ) :=
    (Real.continuous_sqrt.comp h_sq)
  simpa [Real.sqrt_sq_eq_abs, abs_of_nonneg (norm_nonneg _)] using h_sqrt

/-- If the topology on `E` is generated by a family of seminorms `p` and `‖T ·‖` is continuous,
then it is controlled by finitely many seminorms from the family. -/
theorem seminorm_norm_comp_le_finset_sup
    {ι : Type*} (p : ι → Seminorm ℝ E) (hp : WithSeminorms p)
    (T : E →ₗ[ℝ] H)
    (h_sq : Continuous fun f : E => (‖T f‖ ^ 2 : ℝ)) :
    ∃ s : Finset ι, ∃ C : ℝ≥0, C ≠ 0 ∧ (normSeminorm ℝ H).comp T ≤ C • s.sup p := by
  have hq : Continuous ((normSeminorm ℝ H).comp T) := by
    have : Continuous fun f : E => ((normSeminorm ℝ H).comp T) f := by
      simpa using (continuous_norm_of_continuous_norm_sq (E := E) (H := H) T h_sq)
    simpa using this
  exact Seminorm.bound_of_continuous (𝕜 := ℝ) (p := p) (hp := hp) ((normSeminorm ℝ H).comp T) hq

end MinlosGaussianSeminormBounds

end

end OSforGFF
